<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NPNNVAF" failures="2" tests="2" name="Test(failed)" time="56.123" errors="0" timestamp="11 Aug 2018 13:31:58 GMT">
  <testcase classname="Script.TestScript3" name="testTwitterLink" time="8.015">
    <failure type="java.lang.AssertionError" message="expected [Twitter. It&amp;apos;s what&amp;apos;s happening1.] but found [Twitter. It&amp;apos;s what&amp;apos;s happening.]">
      <![CDATA[java.lang.AssertionError: expected [Twitter. It's what's happening1.] but found [Twitter. It's what's happening.]
at Script.TestScript3.testTwitterLink(TestScript3.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testTwitterLink -->
  <testcase classname="Script.TestScript4" name="testInstagramLink" time="37.419">
    <failure type="java.lang.AssertionError" message="expected [Instagram1] but found [Instagram]">
      <![CDATA[java.lang.AssertionError: expected [Instagram1] but found [Instagram]
at Script.TestScript4.testInstagramLink(TestScript4.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testInstagramLink -->
</testsuite> <!-- Test(failed) -->
